export type OfficialDoctorSummary = {
  slug: string;
  nameEn: string;
  nameAr: string;
  specialtyEn: string;
  specialtyAr: string;
  image: string;
  noteEn: string;
  noteAr: string;
};

export const officialDoctors: readonly OfficialDoctorSummary[] = [
  {
    slug: "dr-nael-adel",
    nameEn: "Dr. Nael Adel Ishnineh",
    nameAr: "الدكتور نائل عادل إشنينة",
    specialtyEn: "Dentist · Co-Founder & Clinical Director",
    specialtyAr: "طبيب أسنان · شريك مؤسس ومدير سريري",
    image: "/media/doctors-fast/dr-nael-adel.webp",
    noteEn: "More than two decades of dentistry experience with a strong focus on cosmetic dentistry.",
    noteAr: "خبرة تزيد عن عقدين في طب الأسنان مع تركيز قوي على طب الأسنان التجميلي.",
  },
  {
    slug: "dr-mohammed-hijazi",
    nameEn: "Dr. Mohammed Hijazi",
    nameAr: "الدكتور محمد حجازي",
    specialtyEn: "Dentist · Periodontology",
    specialtyAr: "طبيب أسنان · أمراض اللثة",
    image: "/media/doctors-fast/dr-mohammed-hijazi.webp",
    noteEn: "Dental care with a focus on periodontal health, oral hygiene and restorative treatment.",
    noteAr: "رعاية أسنان مع تركيز على صحة اللثة ونظافة الفم والعلاجات الترميمية.",
  },
  {
    slug: "dr-wallaa-abo-elyazeed",
    nameEn: "Dr. Wallaa Abo Elyazeed",
    nameAr: "د. ولاء أبو اليزيد",
    specialtyEn: "Aesthetic & Dermatologist",
    specialtyAr: "طبيبة تجميل وأمراض جلدية",
    image: "/media/doctors-fast/dr-wallaa-abo-elyazeed-v2.webp",
    noteEn: "Aesthetic and dermatology care at Smile Care Medical Center.",
    noteAr: "رعاية تجميلية وجلدية في مركز سمايل كير الطبي.",
  },
  {
    slug: "dr-javier-hernandez-hernandez",
    nameEn: "Dr. Javier Hernandez Hernandez",
    nameAr: "د. خافيير هيرنانديز هيرنانديز",
    specialtyEn: "Endodontist",
    specialtyAr: "اختصاصي علاج جذور الأسنان",
    image: "/media/doctors-fast/dr-javier-hernandez-hernandez.webp",
    noteEn: "Specialist endodontic and root-canal care with more than 20 years of experience.",
    noteAr: "رعاية تخصصية لعلاج جذور الأسنان والقنوات بخبرة تزيد عن 20 عاماً.",
  },
  {
    slug: "dr-asmaa-shehadeh",
    nameEn: "Dr. Asmaa Shehadeh",
    nameAr: "الدكتورة أسماء شحادة",
    specialtyEn: "Dentist",
    specialtyAr: "طبيبة أسنان",
    image: "/media/doctors-fast/dr-asmaa-shehadeh.webp",
    noteEn: "General, restorative and pediatric-oriented dental care.",
    noteAr: "رعاية أسنان عامة وترميمية مع اهتمام برعاية الأطفال.",
  },
  {
    slug: "dr-mohamed-taha",
    nameEn: "Dr. Mohammed Taha",
    nameAr: "د. محمد طه",
    specialtyEn: "Dentist",
    specialtyAr: "طبيب أسنان",
    image: "/media/doctors-fast/dr-mohamed-taha.webp",
    noteEn: "General, restorative and aesthetic dentistry with advanced training in veneers and smile design.",
    noteAr: "طب أسنان عام وترميمي وتجميلي مع تدريب متقدم في القشور وتصميم الابتسامة.",
  },
  {
    slug: "dr-salma-eltahir",
    nameEn: "Dr. Salma Eltahir",
    nameAr: "د. سلمى الطاهر",
    specialtyEn: "Specialist Pedodontist",
    specialtyAr: "أخصائية طب أسنان الأطفال",
    image: "/media/doctors-fast/dr-salma-eltahir.webp",
    noteEn: "Specialist pediatric dental care.",
    noteAr: "رعاية تخصصية لأسنان الأطفال.",
  },
  {
    slug: "dr-maher-ahmed-khamis",
    nameEn: "Dr. Maher Ahmed Khamis",
    nameAr: "الدكتور ماهر أحمد خميس",
    specialtyEn: "Oral & Maxillofacial Surgeon",
    specialtyAr: "جراح الفم والوجه والفكين",
    image: "/media/doctors-fast/dr-maher-ahmed-khamis.webp",
    noteEn: "Oral and maxillofacial surgery, implants, bone grafting and complex extractions.",
    noteAr: "جراحة الفم والوجه والفكين وزراعة الأسنان وتطعيم العظام والخلع المعقد.",
  },
  {
    slug: "dr-sara-odeh",
    nameEn: "Dr. Sara Odeh",
    nameAr: "د. سارة عودة",
    specialtyEn: "Dentist",
    specialtyAr: "طبيبة أسنان",
    image: "/media/doctors-fast/dr-sara-odeh.webp",
    noteEn: "General dentistry with endodontic, whitening, cosmetic filling and fixed-prosthesis care.",
    noteAr: "طب أسنان عام مع علاج الجذور والتبييض والحشوات التجميلية والتركيبات الثابتة.",
  },
  {
    slug: "dr-mahra-abdullatif-al-shehhi",
    nameEn: "Dr. Mahra Abdullatif Al Shehhi",
    nameAr: "الدكتورة مهرة عبد اللطيف الشحي",
    specialtyEn: "Dentist",
    specialtyAr: "طبيبة أسنان",
    image: "/media/doctors-fast/dr-mahra-abdullatif-al-shehhi.webp",
    noteEn: "General dentistry, aesthetic fillings, whitening, root-canal treatment, crowns and bridges.",
    noteAr: "طب أسنان عام وحشوات تجميلية وتبييض وعلاج عصب وتيجان وجسور.",
  },
  {
    slug: "dr-duaa-kassem",
    nameEn: "Dr. Duaa Kassem",
    nameAr: "د. دعاء قاسم",
    specialtyEn: "Dentist",
    specialtyAr: "طبيبة أسنان",
    image: "/media/doctors-fast/dr-duaa-kassem.jpg",
    noteEn: "Preventive, pediatric and aesthetic dental care.",
    noteAr: "رعاية وقائية وطب أسنان أطفال وعلاجات تجميلية.",
  },
  {
    slug: "dr-syed-anwar",
    nameEn: "Dr. Syed Anwar",
    nameAr: "الدكتور سيد أنور",
    specialtyEn: "Dentist & Implantologist",
    specialtyAr: "طبيب أسنان وأخصائي زراعة أسنان",
    image: "/media/doctors-fast/dr-syed-anwar.webp",
    noteEn: "General dentist and implantologist with more than 9 years of experience.",
    noteAr: "طبيب أسنان عام وأخصائي زراعة أسنان بخبرة تزيد عن 9 سنوات.",
  },
  {
    slug: "dr-mohammed-mwafi",
    nameEn: "Dr. Mohammed Mwafi",
    nameAr: "الدكتور محمد موافي",
    specialtyEn: "Specialist of Orthodontics",
    specialtyAr: "أخصائي تقويم الأسنان",
    image: "/media/doctors-fast/dr-mohammed-mwafi.png",
    noteEn: "Specialist orthodontic care including braces, clear aligners and functional appliances.",
    noteAr: "رعاية تخصصية في تقويم الأسنان تشمل التقويم الثابت والشفاف والأجهزة الوظيفية.",
  },
  {
    slug: "dr-mohammed-ayman-alqasem",
    nameEn: "Dr. Mohammed Ayman Alqasem",
    nameAr: "الدكتور محمد أيمن القاسم",
    specialtyEn: "Dentist",
    specialtyAr: "طبيب أسنان",
    image: "/media/doctors-fast/dr-mohammed-ayman-alqasem.webp",
    noteEn: "General-practice dentistry with endodontic, whitening, cosmetic filling and fixed-prosthesis care.",
    noteAr: "طب أسنان عام مع علاج الجذور والتبييض والحشوات التجميلية والتركيبات الثابتة.",
  },
] as const;
